//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 01:05:57 AM MST 
//


package vnd.virtualarmor.hybridrouter.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for execScripts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="execScripts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}scriptMgmt" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="exec-scripts")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExecScripts", propOrder = {
    "scriptMgmt"
})
public class ExecScripts implements Serializable {

    /**
	 * generated serial id
	 */
	private static final long serialVersionUID = -1707067012866173602L;
	
	@XmlElement(required = true)
    protected List<ScriptMgmt> scriptMgmt;

    /**
     * Gets the value of the scriptMgmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scriptMgmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScriptMgmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScriptMgmt }
     * 
     * 
     */
    public List<ScriptMgmt> getScriptMgmt() {
        if (scriptMgmt == null) {
            scriptMgmt = new ArrayList<ScriptMgmt>();
        }
        return this.scriptMgmt;
    }

}
