//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 01:05:57 AM MST 
//


package vnd.virtualarmor.hybridrouter.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scriptMgmt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scriptMgmt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}script"/>
 *         &lt;element name="scriptVersionSelected" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element ref="{}device"/>
 *         &lt;element name="scriptParams" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}scriptParam" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scriptMgmt", propOrder = {

})
public class ScriptMgmt implements Serializable {

    /**
	 * generated serial id
	 */
	private static final long serialVersionUID = -1015698907820232977L;
	
	@XmlElement(required = true)
    protected Script script;
    protected Float scriptVersionSelected;
    @XmlElement(required = true)
    protected Device device;
    protected ScriptParams scriptParams;

    /**
     * Gets the value of the scriptParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scriptParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScriptParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScriptParams }
     * 
     * 
     */
//    public List<ScriptParams> getScriptParams() {
//        if (scriptParams == null) {
 //       	scriptParams = new ArrayList<ScriptParams>();
  //      }
 //       return this.scriptParams;
 //   }

    
    //jjv end 

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setScript(Script value) {
        this.script = value;
    }

    /**
     * Gets the value of the scriptVersionSelected property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getScriptVersionSelected() {
        return scriptVersionSelected;
    }

    /**
     * Sets the value of the scriptVersionSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setScriptVersionSelected(Float value) {
        this.scriptVersionSelected = value;
    }

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link Device }
     *     
     */
    public Device getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link Device }
     *     
     */
    public void setDevice(Device value) {
        this.device = value;
    }

	public ScriptParams getScriptParams() {
		return scriptParams;
	}

	public void setScriptParams(ScriptParams scriptParams) {
		this.scriptParams = scriptParams;
	}

    /**
     * Gets the value of the scriptParams property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptMgmt.ScriptParams }
     *     
     */
  //jjv  public ScriptMgmt.ScriptParams getScriptParams() {
    //jjv       return scriptParams;
    //jjv   }

    /**
     * Sets the value of the scriptParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptMgmt.ScriptParams }
     *     
     */
    //jjv    public void setScriptParams(ScriptMgmt.ScriptParams value) {
    //jjv        this.scriptParams = value;
    //jjv    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}scriptParam" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    //jjv   @XmlAccessorType(XmlAccessType.FIELD)
    //jjv    @XmlType(name = "", propOrder = {
    //jjv         "scriptParam"
    //jjv     })
    //jjv    public static class ScriptParams {
    //jjv 
    //jjv       protected List<ScriptParams> scriptParam;

        /**
         * Gets the value of the scriptParam property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the scriptParam property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScriptParam().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link generated.ScriptParams }
         * 
         * 
         */
    //jjv         public List<ScriptParams> getScriptParam() {
    //jjv            if (scriptParam == null) {
    //jjv                scriptParam = new ArrayList<ScriptParams>();
    //jjv           }
    //jjv          return this.scriptParam;
    //jjv       }
    //jjv
    //jjv    }

}
