/*
 * File: SnmpStore.js
 * Date: Mon Aug 20 2012 21:13:25 GMT-0600 (Mountain Daylight Time)
 * 
 * This file was generated by Junos Space Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

SnmpStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        SnmpStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'MyStore'
        }, cfg));
    }
});
new SnmpStore();