/*
 * File: snmpForm.ui.js
 * Date: Sun Aug 12 2012 23:02:01 GMT-0600 (Mountain Daylight Time)
 * 
 * This file was generated by Junos Space Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

snmpFormUi = Ext.extend(Ext.form.FormPanel, {
    title: 'SNMP Device Information',
    width: 468,
    height: 282,
    padding: 5,
    frame: true,
    labelAlign: 'right',
    labelWidth: 90,
    closable: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'fieldset',
                title: 'Device Address',
                height: 89,
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'IP Address',
                        anchor: '100%',
                        width: 209,
                        allowBlank: false,
                        flex: 1
                    },
                    {
                        xtype: 'numberfield',
                        fieldLabel: 'Port',
                        anchor: '50%',
                        width: 50
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'OID Value',
                height: 90,
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'OID Key',
                        anchor: '100%'
                    },
                    {
                        xtype: 'displayfield',
                        fieldLabel: 'OID Value',
                        anchor: '100%',
                        value: ''
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 44,
                layout: 'absolute',
                items: [
                    {
                        xtype: 'button',
                        text: 'Submit',
                        x: 200,
                        y: 10
                    }
                ]
            }
        ];
        snmpFormUi.superclass.initComponent.call(this);
    }
});
