/*
 * File: snmpForm.js
 * Date: Sun Aug 12 2012 22:43:52 GMT-0600 (Mountain Daylight Time)
 * 
 * This file was generated by Junos Space Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

snmpForm = Ext.extend(snmpFormUi, {
    initComponent: function() {
        snmpForm.superclass.initComponent.call(this);
    }
});
